/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author BRUCE WANG
 */
public class AOOR extends javax.swing.JFrame {

    Preferences aoor_LRL = Preferences.userRoot().node("AOOR_LRL");
    Preferences aoor_URL = Preferences.userRoot().node("AOOR_URL");
    Preferences aoor_AA = Preferences.userRoot().node("AOOR_AA");
    Preferences aoor_APW = Preferences.userRoot().node("AOOR_APW");
    Preferences aoor_AT = Preferences.userRoot().node("AOOR_AT");
    Preferences aoor_RT = Preferences.userRoot().node("AOOR_RT");
    Preferences aoor_RF = Preferences.userRoot().node("AOOR_RF");
    Preferences aoor_CT = Preferences.userRoot().node("AOOR_CT");
    
    
    
    public AOOR() {
        initComponents();
        jTextField_LRL.setText(aoor_LRL.get(Login_Form.getusername(),""));
        jTextField_URL.setText(aoor_URL.get(Login_Form.getusername(),""));
        jTextField_AA.setText(aoor_AA.get(Login_Form.getusername(),""));
        jTextField_APW.setText(aoor_APW.get(Login_Form.getusername(),""));
        jTextField_AT.setText(aoor_AT.get(Login_Form.getusername(),""));
        jTextField_RT.setText(aoor_RT.get(Login_Form.getusername(),""));
        jTextField_RF.setText(aoor_RF.get(Login_Form.getusername(),""));
        jTextField_CT.setText(aoor_CT.get(Login_Form.getusername(),""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_LRL = new javax.swing.JTextField();
        jTextField_URL = new javax.swing.JTextField();
        jTextField_AA = new javax.swing.JTextField();
        jTextField_APW = new javax.swing.JTextField();
        jTextField_AT = new javax.swing.JTextField();
        jTextField_RT = new javax.swing.JTextField();
        jTextField_RF = new javax.swing.JTextField();
        jTextField_CT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setText("Lower Rate Limit :");

        jLabel2.setText("Upper Rate Limit :");

        jLabel3.setText("Atrial Amplitude :");

        jLabel4.setText("Atrial Pules Width :");

        jLabel5.setText("Activity Threshold :");

        jLabel6.setText("Reaction Time :");

        jLabel7.setText("Response Factor :");

        jLabel8.setText("Recovery Time :");

        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ENTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ENTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("ENTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("ENTER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("ENTER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("ENTER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel9.setText("BACK");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jTextField_AA)
                    .addComponent(jTextField_LRL)
                    .addComponent(jTextField_APW)
                    .addComponent(jTextField_AT)
                    .addComponent(jTextField_RT)
                    .addComponent(jTextField_RF)
                    .addComponent(jTextField_CT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_AA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_APW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_AT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_RT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_RF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_CT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String CT = jTextField_CT.getText();
        int ct = Integer.parseInt(CT);
        if (ct>=2 && ct<=16 && ct%1==0){
        aoor_CT.put(Login_Form.getusername() , CT);
        jTextField_CT.setText(aoor_CT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 2to 16, the increment is 1 "," Error", 3 );
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        //System.out.println(lrl);
        
        if ((lrl>50 && lrl<90 && lrl%1==0)){
        aoor_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(aoor_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (lrl>30 && lrl<50 && lrl%5==0){
        aoor_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(aoor_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (lrl>90 && lrl<175 && lrl%5==0){
        aoor_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(aoor_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String URL = jTextField_URL.getText();
        int url = Integer.parseInt(URL);
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        if (lrl>url){
            JOptionPane.showMessageDialog(null, "The upper rate limit is smaller than lower","Error", 3 );
        }else if (url<50 || url>175 || url%5!=0 || URL.trim().equals("")){
        JOptionPane.showMessageDialog(null, "Out of range, The value must between 50 to 175 the increment is 5","Error", 3 );
    }else{ aoor_URL.put(Login_Form.getusername() , URL);
        jTextField_URL.setText(aoor_URL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String AA  = jTextField_AA.getText();
         float aa = Float.valueOf(AA);
         if ((aa>0.5 && aa<3.2 && (aa*100)%10==0)){
        aoor_AA.put(Login_Form.getusername() , AA);
        jTextField_AA.setText(aoor_AA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (aa>3.5 && aa<7 && aa%0.5==0){
        aoor_AA.put(Login_Form.getusername() , AA);
        jTextField_AA.setText(aoor_AA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 ); 
    }else if (aa==0){
        aoor_AA.put(Login_Form.getusername() , AA);
        jTextField_AA.setText(aoor_AA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "the input is OFF, 0.5V-3.2V with increment of 0.1V. in between 3.5V-7.0V with increment of 0.5V.  ","Error", 3 );}
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String APW = jTextField_APW.getText();
        float apw = Float.valueOf(APW);
        
        if("0.05".equals(APW)){
            aoor_APW.put(Login_Form.getusername() ,APW);
        jTextField_APW.setText(aoor_APW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else if(apw>0.1 && apw<1.9 && (apw*100)%10==0){
            aoor_APW.put(Login_Form.getusername() , APW);
        jTextField_APW.setText(aoor_APW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else{JOptionPane.showMessageDialog(null, "Out of range, The value must between 0.1to 1.9 the increment is 0.1 or 0.05"," Error", 3 );}                                      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String AT = jTextField_AT.getText();
   
        if ("V-low".equals(AT) || "Low".equals(AT)|| "Med-Low".equals(AT) || "Med".equals(AT) || "Med-High".equals(AT) || "High".equals(AT)|| "V-High".equals(AT) ){
        aoor_AT.put(Login_Form.getusername() , AT);
        jTextField_AT.setText(aoor_AT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must be V-Low, Low, Med-Low, Med,Med-High, High, V-High "," Error", 3 );
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String RT = jTextField_RT.getText();
        int rt = Integer.parseInt(RT);
        if (rt>=10 && rt<=50 && rt%10==0){
        aoor_RT.put(Login_Form.getusername() , RT);
        jTextField_RT.setText(aoor_RT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 10to 50, the increment is 10 "," Error", 3 );
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String RF = jTextField_RF.getText();
        int rf = Integer.parseInt(RF);
        if (rf>=1 && rf<=16 && rf%1==0){
        aoor_RF.put(Login_Form.getusername() , RF);
        jTextField_RF.setText(aoor_RF.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 1to 16, the increment is 1 "," Error", 3 );
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Menu_Form form = new Menu_Form();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AOOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_AA;
    private javax.swing.JTextField jTextField_APW;
    private javax.swing.JTextField jTextField_AT;
    private javax.swing.JTextField jTextField_CT;
    private javax.swing.JTextField jTextField_LRL;
    private javax.swing.JTextField jTextField_RF;
    private javax.swing.JTextField jTextField_RT;
    private javax.swing.JTextField jTextField_URL;
    // End of variables declaration//GEN-END:variables
}
