/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author BRUCE WANG
 */
public class DOO extends javax.swing.JFrame {

    Preferences doo_LRL = Preferences.userRoot().node("DOO_LRL");
    Preferences doo_URL = Preferences.userRoot().node("DOO_URL");
    Preferences doo_FAD = Preferences.userRoot().node("DOO_FAD");
    Preferences doo_AA = Preferences.userRoot().node("DOO_AA");
    Preferences doo_APW = Preferences.userRoot().node("DOO_APW");
    Preferences doo_VA = Preferences.userRoot().node("DOO_ARP");
    Preferences doo_VPW = Preferences.userRoot().node("DOO_APW");
    public DOO() {
        initComponents();
        jTextField_LRL.setText(doo_LRL.get(Login_Form.getusername(),""));
        jTextField_URL.setText(doo_URL.get(Login_Form.getusername(),""));
        jTextField_FAD.setText(doo_FAD.get(Login_Form.getusername(),""));
        jTextField_AA.setText(doo_AA.get(Login_Form.getusername(),""));
        jTextField_APW.setText(doo_APW.get(Login_Form.getusername(),""));
        jTextField_VA.setText(doo_VA.get(Login_Form.getusername(),""));
        jTextField_VPW.setText(doo_VPW.get(Login_Form.getusername(),""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_LRL = new javax.swing.JTextField();
        jTextField_URL = new javax.swing.JTextField();
        jTextField_FAD = new javax.swing.JTextField();
        jTextField_AA = new javax.swing.JTextField();
        jTextField_APW = new javax.swing.JTextField();
        jTextField_VA = new javax.swing.JTextField();
        jTextField_VPW = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setText("Lower Rate Limit :");

        jLabel2.setText("Upper Rate Limit :");

        jLabel3.setText("Fixed AV Delay :");

        jLabel4.setText("Atrial Amplitude :");

        jLabel5.setText("Atrial Pules Width :");

        jLabel6.setText("Ventricular Amplitude :");

        jLabel7.setText("Ventricular Pulse Width :");

        jTextField_LRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LRLActionPerformed(evt);
            }
        });

        jTextField_VA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_VAActionPerformed(evt);
            }
        });

        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ENTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ENTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("ENTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("ENTER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("ENTER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel8.setText("BACK");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_FAD, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_URL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_AA, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(82, 82, 82)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_VA, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_APW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_VPW))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_FAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_AA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_APW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_VA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_VPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_LRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LRLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LRLActionPerformed

    private void jTextField_VAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_VAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_VAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        //System.out.println(lrl);
        
        if ((lrl>50 && lrl<90 && lrl%1==0)){
        doo_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(doo_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (lrl>30 && lrl<50 && lrl%5==0){
        doo_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(doo_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (lrl>90 && lrl<175 && lrl%5==0){
        doo_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(doo_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}                                            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String URL = jTextField_URL.getText();
        int url = Integer.parseInt(URL);
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        if (lrl>url){
            JOptionPane.showMessageDialog(null, "The upper rate limit is smaller than lower","Error", 3 );
        }else if (url<50 || url>175 || url%5!=0 || URL.trim().equals("")){
        JOptionPane.showMessageDialog(null, "Out of range, The value must between 50 to 175 the increment is 5","Error", 3 );
    }else{ doo_URL.put(Login_Form.getusername() , URL);
        jTextField_URL.setText(doo_URL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String FAD = jTextField_FAD.getText();
        int fad = Integer.parseInt(FAD);
        if (fad>=70 && fad <=300 && fad%10==0){
        doo_FAD.put(Login_Form.getusername() , FAD);
        jTextField_FAD.setText(doo_FAD.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 70 to 300, the increment is 10 "," Error", 3 );
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String AA  = jTextField_AA.getText();
         float aa = Float.valueOf(AA);
         if ((aa>0.5 && aa<3.2 && (aa*100)%10==0)){
        doo_AA.put(Login_Form.getusername() , AA);
        jTextField_AA.setText(doo_AA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (aa>3.5 && aa<7 && aa%0.5==0){
        doo_AA.put(Login_Form.getusername() , AA);
        jTextField_AA.setText(doo_AA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 ); 
    }else if (aa==0){
        doo_AA.put(Login_Form.getusername() , AA);
        jTextField_AA.setText(doo_AA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "the input is OFF, 0.5V-3.2V with increment of 0.1V. in between 3.5V-7.0V with increment of 0.5V.  ","Error", 3 );}
                               
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String APW = jTextField_APW.getText();
        float apw = Float.valueOf(APW);
        
        if("0.05".equals(APW)){
            doo_APW.put(Login_Form.getusername() ,APW);
        jTextField_APW.setText(doo_APW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else if(apw>0.1 && apw<1.9 && (apw*100)%10==0){
            doo_APW.put(Login_Form.getusername() , APW);
        jTextField_APW.setText(doo_APW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else{JOptionPane.showMessageDialog(null, "Out of range, The value must between 0.1to 1.9 the increment is 0.1 or 0.05"," Error", 3 );}
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String VA  = jTextField_VA.getText();
         float va = Float.valueOf(VA);
         if ((va>0.5 && va<3.2 && (va*100)%10==0)){
        doo_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(doo_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (va>3.5 && va<7 && va%0.5==0){
        doo_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(doo_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (va==0){
        doo_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(doo_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "the input is OFF, 0.5V-3.2V with increment of 0.1V. in between 3.5V-7.0V with increment of 0.5V.  ","Error", 3 );}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String VPW = jTextField_VPW.getText();
        float vpw = Float.valueOf(VPW);
        
        if("0.05".equals(VPW)){
            doo_VPW.put(Login_Form.getusername() , VPW);
        jTextField_VPW.setText(doo_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else if(vpw>0.1 && vpw<1.9 && (vpw*100)%10==0){
            doo_VPW.put(Login_Form.getusername() , VPW);
        jTextField_VPW.setText(doo_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else{JOptionPane.showMessageDialog(null, "Out of range, The value must between 0.1to 1.9 the increment is 0.1 or 0.05"," Error", 3 );}
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Menu_Form form = new Menu_Form();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_AA;
    private javax.swing.JTextField jTextField_APW;
    private javax.swing.JTextField jTextField_FAD;
    private javax.swing.JTextField jTextField_LRL;
    private javax.swing.JTextField jTextField_URL;
    private javax.swing.JTextField jTextField_VA;
    private javax.swing.JTextField jTextField_VPW;
    // End of variables declaration//GEN-END:variables
}
