/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author BRUCE WANG
 */
public class VOO extends javax.swing.JFrame {

    Preferences voo_LRL = Preferences.userRoot().node("VOO_LRL");
    Preferences voo_URL = Preferences.userRoot().node("VOO_URL");
    Preferences voo_VA = Preferences.userRoot().node("VOO_VA");
    Preferences voo_VPW = Preferences.userRoot().node("VOO_VPW");
    public VOO() {
        initComponents();
        jTextField_LRL.setText(voo_LRL.get(Login_Form.getusername(),""));
        jTextField_URL.setText(voo_URL.get(Login_Form.getusername(),""));
        jTextField_VA.setText(voo_VA.get(Login_Form.getusername(),""));
        jTextField_VPW.setText(voo_VPW.get(Login_Form.getusername(),""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_LRL = new javax.swing.JTextField();
        jTextField_URL = new javax.swing.JTextField();
        jTextField_VA = new javax.swing.JTextField();
        jTextField_VPW = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setText("Lower Rate Limit :");

        jLabel2.setText("Upper Rate Limit :");

        jLabel3.setText("Ventricular Amplitude :");

        jLabel4.setText("Ventricular Pulse Width :");

        jLabel5.setText("BACK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jTextField_LRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LRLActionPerformed(evt);
            }
        });

        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ENTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ENTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_VPW, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jTextField_VA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_URL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_LRL, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_VA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_VPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_LRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LRLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LRLActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        //System.out.println(lrl);
        
        if ((lrl>50 && lrl<90 && lrl%1==0)){
        voo_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(voo_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (lrl>30 && lrl<50 && lrl%5==0){
        voo_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(voo_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (lrl>90 && lrl<175 && lrl%5==0){
        voo_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(voo_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "Out of range, If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String URL = jTextField_URL.getText();
        int url = Integer.parseInt(URL);
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        if (lrl>url){
            JOptionPane.showMessageDialog(null, "The upper rate limit is smaller than lower","Error", 3 );
        }else if (url<50 || url>175 || url%5!=0 || URL.trim().equals("")){
        JOptionPane.showMessageDialog(null, "Out of range, The value must between 50 to 175 and the increment is 5","Error", 3 );
    }else{ voo_URL.put(Login_Form.getusername() , URL);
        jTextField_URL.setText(voo_URL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String VA  = jTextField_VA.getText();
         float va = Float.valueOf(VA);
         if ((va>0.5 && va<3.2 && (va*100)%10==0)){
        voo_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(voo_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (va>3.5 && va<7 && va%0.5==0){
        voo_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(voo_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (va==0){
        voo_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(voo_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "the input is OFF, 0.5V-3.2V with increment of 0.1V. in between 3.5V-7.0V with increment of 0.5V.  ","Error", 3 );}
                                                 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String VPW = jTextField_VPW.getText();
        float vpw = Float.valueOf(VPW);
        System.out.println((vpw==0.05));
        
       if("0.05".equals(VPW)){
        voo_VPW.put(Login_Form.getusername() , VPW);
        jTextField_VPW.setText(voo_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else if(vpw>0.1 && vpw<1.9 && (vpw*100)%10 ==0){
            voo_VPW.put(Login_Form.getusername() , VPW);
        jTextField_VPW.setText(voo_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else{JOptionPane.showMessageDialog(null, "Out of range, The value must between 0.1to 1.9 the increment is 0.1 or 0.05"," Error", 3 );}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Menu_Form form = new Menu_Form();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_LRL;
    private javax.swing.JTextField jTextField_URL;
    private javax.swing.JTextField jTextField_VA;
    private javax.swing.JTextField jTextField_VPW;
    // End of variables declaration//GEN-END:variables
}
