/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author BRUCE WANG
 */
public class VOOR extends javax.swing.JFrame {

    Preferences voor_LRL = Preferences.userRoot().node("VOOR_LRL");
    Preferences voor_URL = Preferences.userRoot().node("VOOR_URL");
    Preferences voor_VA = Preferences.userRoot().node("VOOR_VA");
    Preferences voor_VPW = Preferences.userRoot().node("VOOR_VPW");
    Preferences voor_AT = Preferences.userRoot().node("VOOR_AT");
    Preferences voor_RT = Preferences.userRoot().node("VOOR_RT");
    Preferences voor_RF = Preferences.userRoot().node("VOOR_RF");
    Preferences voor_CT = Preferences.userRoot().node("VOOR_CT");
    public VOOR() {
        initComponents();
        jTextField_LRL.setText(voor_LRL.get(Login_Form.getusername(),""));
        jTextField_URL.setText(voor_URL.get(Login_Form.getusername(),""));
        jTextField_VA.setText(voor_VA.get(Login_Form.getusername(),""));
        jTextField_VPW.setText(voor_VPW.get(Login_Form.getusername(),""));
        jTextField_AT.setText(voor_AT.get(Login_Form.getusername(),""));
        jTextField_RT.setText(voor_RT.get(Login_Form.getusername(),""));
        jTextField_RF.setText(voor_RF.get(Login_Form.getusername(),""));
        jTextField_CT.setText(voor_CT.get(Login_Form.getusername(),""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_LRL = new javax.swing.JTextField();
        jTextField_URL = new javax.swing.JTextField();
        jTextField_VA = new javax.swing.JTextField();
        jTextField_VPW = new javax.swing.JTextField();
        jTextField_AT = new javax.swing.JTextField();
        jTextField_RT = new javax.swing.JTextField();
        jTextField_RF = new javax.swing.JTextField();
        jTextField_CT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setText("Lower Rate Limit :");

        jLabel2.setText("Upper Rate Limit :");

        jLabel3.setText("Ventricular Amplitude :");

        jLabel4.setText("Ventricular Pules Width :");

        jLabel5.setText("Activity Threshold :");

        jLabel6.setText("Reaction Time :");

        jLabel7.setText("Response Factor :");

        jLabel8.setText("Recovery Time :");

        jTextField_AT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ATActionPerformed(evt);
            }
        });

        jLabel9.setText("BACK");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ENTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ENTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("ENTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("ENTER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("ENTER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("ENTER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(173, 173, 173)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_LRL, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jTextField_URL)
                            .addComponent(jTextField_VA)
                            .addComponent(jTextField_VPW)
                            .addComponent(jTextField_AT)
                            .addComponent(jTextField_RT)
                            .addComponent(jTextField_RF)
                            .addComponent(jTextField_CT)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_VA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_VPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_AT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_RT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_RF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_CT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ATActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        //System.out.println(lrl);
        
        if ((lrl>50 && lrl<90 && lrl%1==0)){
        voor_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(voor_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (lrl>30 && lrl<50 && lrl%5==0){
        voor_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(voor_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (lrl>90 && lrl<175 && lrl%5==0){
        voor_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(voor_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String URL = jTextField_URL.getText();
        int url = Integer.parseInt(URL);
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        if (lrl>url){
            JOptionPane.showMessageDialog(null, "The upper rate limit is smaller than lower","Error", 3 );
        }else if (url<50 || url>175 || url%5!=0 || URL.trim().equals("")){
        JOptionPane.showMessageDialog(null, "Out of range, The value must between 50 to 175 the increment is 5","Error", 3 );
    }else{ voor_URL.put(Login_Form.getusername() , URL);
        jTextField_URL.setText(voor_URL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String VA  = jTextField_VA.getText();
         float aa = Float.valueOf(VA);
         if ((aa>0.5 && aa<3.2 && (aa*100)%10==0)){
        voor_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(voor_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (aa>3.5 && aa<7 && aa%0.5==0){
        voor_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(voor_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 ); 
    }else if (aa==0){
        voor_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(voor_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "the input is OFF, 0.5V-3.2V with increment of 0.1V. in between 3.5V-7.0V with increment of 0.5V.  ","Error", 3 );}
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String VPW = jTextField_VPW.getText();
        float apw = Float.valueOf(VPW);
        
        if("0.05".equals(VPW)){
            voor_VPW.put(Login_Form.getusername() ,VPW);
        jTextField_VPW.setText(voor_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else if(apw>0.1 && apw<1.9 && (apw*100)%10==0){
            voor_VPW.put(Login_Form.getusername() , VPW);
        jTextField_VPW.setText(voor_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else{JOptionPane.showMessageDialog(null, "Out of range, The value must between 0.1to 1.9 the increment is 0.1 or 0.05"," Error", 3 );}
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String AT = jTextField_AT.getText();
   
        if ("V-low".equals(AT) || "Low".equals(AT)|| "Med-Low".equals(AT) || "Med".equals(AT) || "Med-High".equals(AT) || "High".equals(AT)|| "V-High".equals(AT) ){
        voor_AT.put(Login_Form.getusername() , AT);
        jTextField_AT.setText(voor_AT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must be V-Low, Low, Med-Low, Med,Med-High, High, V-High "," Error", 3 );
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String RT = jTextField_RT.getText();
        int rt = Integer.parseInt(RT);
        if (rt>=10 && rt<=50 && rt%10==0){
        voor_RT.put(Login_Form.getusername() , RT);
        jTextField_RT.setText(voor_RT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 10to 50, the increment is 10 "," Error", 3 );
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String RF = jTextField_RF.getText();
        int rf = Integer.parseInt(RF);
        if (rf>=1 && rf<=16 && rf%1==0){
        voor_RF.put(Login_Form.getusername() , RF);
        jTextField_RF.setText(voor_RF.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 1to 16, the increment is 1 "," Error", 3 );
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String CT = jTextField_CT.getText();
        int ct = Integer.parseInt(CT);
        if (ct>=2 && ct<=16 && ct%1==0){
        voor_CT.put(Login_Form.getusername() , CT);
        jTextField_CT.setText(voor_CT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 2to 16, the increment is 1 "," Error", 3 );
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Menu_Form form = new Menu_Form();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_AT;
    private javax.swing.JTextField jTextField_CT;
    private javax.swing.JTextField jTextField_LRL;
    private javax.swing.JTextField jTextField_RF;
    private javax.swing.JTextField jTextField_RT;
    private javax.swing.JTextField jTextField_URL;
    private javax.swing.JTextField jTextField_VA;
    private javax.swing.JTextField jTextField_VPW;
    // End of variables declaration//GEN-END:variables
}
