/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;


import java.awt.Color;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author April
 */
public class VVI extends javax.swing.JFrame {
    Preferences vvi_LRL = Preferences.userRoot().node("VVI_LRL");
    Preferences vvi_URL = Preferences.userRoot().node("VVI_URL");
    Preferences vvi_VA = Preferences.userRoot().node("VVI_VA");
    Preferences vvi_VPW = Preferences.userRoot().node("VVI_VPW");
    Preferences vvi_VS = Preferences.userRoot().node("VVI_VS");
    Preferences vvi_VRP = Preferences.userRoot().node("VVI_VRP");
    Preferences vvi_HY = Preferences.userRoot().node("VVI_HY");
    Preferences vvi_RS = Preferences.userRoot().node("VVI_RS");
    /**
     * Creates new form VVI
     */
    public VVI() {
        initComponents();
        jTextField_LRL.setText(vvi_LRL.get(Login_Form.getusername(),""));
        jTextField_URL.setText(vvi_URL.get(Login_Form.getusername(),""));
        jTextField_VA.setText(vvi_VA.get(Login_Form.getusername(),""));
        jTextField_VPW.setText(vvi_VPW.get(Login_Form.getusername(),""));
        jTextField_VS.setText(vvi_VS.get(Login_Form.getusername(),""));
        jTextField_VRP.setText(vvi_VRP.get(Login_Form.getusername(),""));
        jTextField_HY.setText(vvi_HY.get(Login_Form.getusername(),""));
        jTextField_RS.setText(vvi_RS.get(Login_Form.getusername(),""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_LRL = new javax.swing.JTextField();
        jTextField_VA = new javax.swing.JTextField();
        jTextField_VRP = new javax.swing.JTextField();
        jTextField_URL = new javax.swing.JTextField();
        jLabelB = new javax.swing.JLabel();
        jButtonEnter0 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_VPW = new javax.swing.JTextField();
        jButtonEnter2 = new javax.swing.JButton();
        jButtonEnter1 = new javax.swing.JButton();
        jButtonEnter4 = new javax.swing.JButton();
        jButtonEnter3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField_VS = new javax.swing.JTextField();
        jButtonEnter5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_HY = new javax.swing.JTextField();
        jTextField_RS = new javax.swing.JTextField();
        jButtonEnter7 = new javax.swing.JButton();
        jButtonEnter6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 88, 178));

        jLabel3.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Lower Rate Limit :");

        jLabel5.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Ventricular Pulse Width :");

        jLabel6.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Ventricular Amplitude :");

        jLabel7.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Upper Rate Limit :");

        jTextField_LRL.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_LRL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LRLKeyTyped(evt);
            }
        });

        jTextField_VA.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_VAActionPerformed(evt);
            }
        });
        jTextField_VA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VAKeyTyped(evt);
            }
        });

        jTextField_VRP.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VRP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VRPKeyTyped(evt);
            }
        });

        jTextField_URL.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_URL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_URLKeyTyped(evt);
            }
        });

        jLabelB.setFont(new java.awt.Font("Khmer MN", 1, 24)); // NOI18N
        jLabelB.setForeground(new java.awt.Color(204, 255, 255));
        jLabelB.setText(">>Back");
        jLabelB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBMouseExited(evt);
            }
        });

        jButtonEnter0.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter0.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter0.setText("Enter");
        jButtonEnter0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter0ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("VRP :");

        jTextField_VPW.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VPWKeyTyped(evt);
            }
        });

        jButtonEnter2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter2.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter2.setText("Enter");
        jButtonEnter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter2ActionPerformed(evt);
            }
        });

        jButtonEnter1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter1.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter1.setText("Enter");
        jButtonEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter1ActionPerformed(evt);
            }
        });

        jButtonEnter4.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter4.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter4.setText("Enter");
        jButtonEnter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter4ActionPerformed(evt);
            }
        });

        jButtonEnter3.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter3.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter3.setText("Enter");
        jButtonEnter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Ventricular Sensitivity :");

        jTextField_VS.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VSKeyTyped(evt);
            }
        });

        jButtonEnter5.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter5.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter5.setText("Enter");
        jButtonEnter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Hysteresis :");

        jLabel11.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Rate Smoothing :");

        jTextField_HY.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_HY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_HYKeyTyped(evt);
            }
        });

        jTextField_RS.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_RS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_RSKeyTyped(evt);
            }
        });

        jButtonEnter7.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter7.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter7.setText("Enter");
        jButtonEnter7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter7ActionPerformed(evt);
            }
        });

        jButtonEnter6.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter6.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter6.setText("Enter");
        jButtonEnter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(20, 20, 20)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel7))))
                                            .addGap(32, 32, 32))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_VRP, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEnter5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_VPW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_VA, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_VS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jButtonEnter0, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonEnter2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonEnter3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonEnter4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_RS, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEnter7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_HY, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEnter6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelB)
                                .addGap(223, 223, 223))
                            .addComponent(jButtonEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter0))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_VA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter2))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_VPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_VS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_VRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEnter5)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_HY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButtonEnter6))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_RS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButtonEnter7))
                .addGap(59, 59, 59)
                .addComponent(jLabelB)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_VAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_VAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_VAActionPerformed

    private void jButtonEnter0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter0ActionPerformed
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        //System.out.println(lrl);
        
        
        if ((lrl>50 && lrl<90 && lrl%1==0)){
        vvi_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(vvi_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (lrl>30 && lrl<50 && lrl%5==0){
        vvi_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(vvi_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (lrl>90 && lrl<175 && lrl%5==0){
        vvi_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(vvi_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}
    }//GEN-LAST:event_jButtonEnter0ActionPerformed

    private void jButtonEnter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter2ActionPerformed
        String VA  = jTextField_VA.getText();
         float va = Float.valueOf(VA);
         if ((va>0.5 && va<3.2 && (va*100)%10==0)){
        vvi_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(vvi_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (va>3.5 && va<7 && va%0.5==0){
        vvi_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(vvi_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (va==0){
        vvi_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(vvi_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "the input is OFF, 0.5V-3.2V with increment of 0.1V. in between 3.5V-7.0V with increment of 0.5V.  ","Error", 3 );}
    }//GEN-LAST:event_jButtonEnter2ActionPerformed

    private void jButtonEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter1ActionPerformed
        String URL = jTextField_URL.getText();
        int url = Integer.parseInt(URL);
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        if (lrl>url){
            JOptionPane.showMessageDialog(null, "The upper rate limit is smaller than lower","Error", 3 );
        }else if (url<50 || url>175 || url%5!=0 || URL.trim().equals("")){
        JOptionPane.showMessageDialog(null, "Out of rang The value must between 50 to 175 and the increment is 5"," Error ", 3 );
    }else{ vvi_URL.put(Login_Form.getusername() , URL);
        jTextField_URL.setText(vvi_URL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButtonEnter1ActionPerformed

    private void jButtonEnter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter4ActionPerformed
        String VS = jTextField_VS.getText();
        float vs = Float.valueOf(VS);
        if (vs==0.25 || vs==0.5 || vs==0.75){
        vvi_VS.put(Login_Form.getusername() , VS);
        jTextField_VS.setText(vvi_VS.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       } else if (vs<=10 && vs>=1.0 && vs%0.5==0){
         vvi_VS.put(Login_Form.getusername() , VS); 
         jTextField_VS.setText(vvi_VS.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 1to 10, the increment is 0.5 or it is 0.25.0.5 0.75 "," Error", 3 );
       }
    }//GEN-LAST:event_jButtonEnter4ActionPerformed

    private void jButtonEnter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter3ActionPerformed
        String VPW = jTextField_VPW.getText();
        float vpw = Float.valueOf(VPW);
        
        if("0.05".equals(VPW)){
            vvi_VPW.put(Login_Form.getusername() , VPW);
        jTextField_VPW.setText(vvi_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else if(vpw>0.1 && vpw<1.9 && (vpw*100)%10==0){
            vvi_VPW.put(Login_Form.getusername() , VPW);
        jTextField_VPW.setText(vvi_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else{JOptionPane.showMessageDialog(null, "Out of range, The value must between 0.1to 1.9 the increment is 0.1 or 0.05"," Error", 3 );}
        
        
    }//GEN-LAST:event_jButtonEnter3ActionPerformed

    private void jLabelBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBMouseClicked
          Menu_Form form = new Menu_Form();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
    }//GEN-LAST:event_jLabelBMouseClicked

    private void jLabelBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBMouseEntered
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabelB.setBorder(label_border);
    }//GEN-LAST:event_jLabelBMouseEntered

    private void jLabelBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBMouseExited
        Border label_create_accont_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabelB.setBorder(label_create_accont_border);
    }//GEN-LAST:event_jLabelBMouseExited

    private void jTextField_LRLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LRLKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_LRLKeyTyped

    private void jTextField_URLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_URLKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_URLKeyTyped

    private void jTextField_VAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VAKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_VAKeyTyped

    private void jTextField_VPWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VPWKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_VPWKeyTyped

    private void jTextField_VRPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VRPKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_VRPKeyTyped

    private void jTextField_VSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VSKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_VSKeyTyped

    private void jButtonEnter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter5ActionPerformed
        String VRP = jTextField_VRP.getText();
        float vrp = Float.valueOf(VRP);
        
        if (vrp<150 || vrp>500 || vrp%10 !=0){
        JOptionPane.showMessageDialog(null, "Out of range, The value must between 150to 500 the increment is 10"," Error", 3 );
    }else{ vvi_VRP.put(Login_Form.getusername() , VRP);
        jTextField_VRP.setText(vvi_VRP.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButtonEnter5ActionPerformed

    private void jTextField_HYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HYKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_HYKeyTyped

    private void jTextField_RSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_RSKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_RSKeyTyped

    private void jButtonEnter7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter7ActionPerformed
        String RS = jTextField_RS.getText();
        int rs = Integer.parseInt(RS);
        if (rs==0 || rs==3|| rs==6|| rs==9|| rs==12|| rs==15|| rs==18|| rs==21|| rs==25 ){
        vvi_RS.put(Login_Form.getusername() , RS);
        jTextField_RS.setText(vvi_RS.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must be0, 3, 6, 9, 12, 15, 18, 21,25 "," Error", 3 );
       }
    }//GEN-LAST:event_jButtonEnter7ActionPerformed

    private void jButtonEnter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter6ActionPerformed
        String HY = jTextField_HY.getText();
        int hy = Integer.parseInt(HY);
        //System.out.println(lrl);
        
        if ((hy>50 && hy<90 && hy%1==0)){
        vvi_HY.put(Login_Form.getusername() , HY);
        jTextField_HY.setText(vvi_HY.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (hy>30 && hy<50 && hy%5==0){
        vvi_HY.put(Login_Form.getusername() , HY);
        jTextField_HY.setText(vvi_HY.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (hy>90 && hy<175 && hy%5==0){
        vvi_HY.put(Login_Form.getusername() , HY);
        jTextField_HY.setText(vvi_HY.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}
    }//GEN-LAST:event_jButtonEnter6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter0;
    private javax.swing.JButton jButtonEnter1;
    private javax.swing.JButton jButtonEnter2;
    private javax.swing.JButton jButtonEnter3;
    private javax.swing.JButton jButtonEnter4;
    private javax.swing.JButton jButtonEnter5;
    private javax.swing.JButton jButtonEnter6;
    private javax.swing.JButton jButtonEnter7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_HY;
    private javax.swing.JTextField jTextField_LRL;
    private javax.swing.JTextField jTextField_RS;
    private javax.swing.JTextField jTextField_URL;
    private javax.swing.JTextField jTextField_VA;
    private javax.swing.JTextField jTextField_VPW;
    private javax.swing.JTextField jTextField_VRP;
    private javax.swing.JTextField jTextField_VS;
    // End of variables declaration//GEN-END:variables
}
