/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;


import java.awt.Color;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author April
 */
public class VVIR extends javax.swing.JFrame {
    
    Preferences vvir_LRL = Preferences.userRoot().node("VVIR_LRL");
    Preferences vvir_URL = Preferences.userRoot().node("VVIR_URL");
    Preferences vvir_VA = Preferences.userRoot().node("VVIR_VA");
    Preferences vvir_VPW = Preferences.userRoot().node("VVIR_VPW");
    Preferences vvir_VS = Preferences.userRoot().node("VVIR_VS");
    Preferences vvir_VRP = Preferences.userRoot().node("VVIR_VRP");
    Preferences vvir_HY = Preferences.userRoot().node("VVIR_HY");
    Preferences vvir_RS = Preferences.userRoot().node("VVIR_RS");
    Preferences vvir_AT = Preferences.userRoot().node("VVIR_AT");
    Preferences vvir_RT = Preferences.userRoot().node("VVIR_RT");
    Preferences vvir_RF = Preferences.userRoot().node("VVIR_RF");
    Preferences vvir_CT = Preferences.userRoot().node("VVIR_CT");

    /**
     * Creates new form AAI
     */
    public VVIR() {
        initComponents();
        jTextField_LRL.setText(vvir_LRL.get(Login_Form.getusername(),""));
        jTextField_URL.setText(vvir_URL.get(Login_Form.getusername(),""));
        jTextField_VA.setText(vvir_VA.get(Login_Form.getusername(),""));
        jTextField_VPW.setText(vvir_VPW.get(Login_Form.getusername(),""));
        jTextField_VS.setText(vvir_VS.get(Login_Form.getusername(),""));
        jTextField_VRP.setText(vvir_VRP.get(Login_Form.getusername(),""));
        jTextField_HY.setText(vvir_HY.get(Login_Form.getusername(),""));
        jTextField_RS.setText(vvir_RS.get(Login_Form.getusername(),""));
        jTextField_AT.setText(vvir_AT.get(Login_Form.getusername(),""));
        jTextField_RT.setText(vvir_RT.get(Login_Form.getusername(),""));
        jTextField_RF.setText(vvir_RF.get(Login_Form.getusername(),""));
        jTextField_CT.setText(vvir_CT.get(Login_Form.getusername(),""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_LRL = new javax.swing.JTextField();
        jTextField_VPW = new javax.swing.JTextField();
        jTextField_URL = new javax.swing.JTextField();
        jTextField_VA = new javax.swing.JTextField();
        jLabelB = new javax.swing.JLabel();
        jButtonEnter3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_VRP = new javax.swing.JTextField();
        jButtonEnter2 = new javax.swing.JButton();
        jButtonEnter0 = new javax.swing.JButton();
        jButtonEnter1 = new javax.swing.JButton();
        jButtonEnter4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_VS = new javax.swing.JTextField();
        jButtonEnter5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_HY = new javax.swing.JTextField();
        jTextField_RT = new javax.swing.JTextField();
        jButtonEnter6 = new javax.swing.JButton();
        jButtonEnter7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField_AT = new javax.swing.JTextField();
        jButtonEnter8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField_RS = new javax.swing.JTextField();
        jButtonEnter9 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_RF = new javax.swing.JTextField();
        jTextField_CT = new javax.swing.JTextField();
        jButtonEnter10 = new javax.swing.JButton();
        jButtonEnter11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 88, 178));

        jLabel3.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Lower Rate Limit :");

        jLabel4.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Ventricular Pules Width :");

        jLabel7.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Upper Rate Limit :");

        jLabel8.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Ventricular Amplitude :");

        jTextField_LRL.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_LRL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LRLKeyTyped(evt);
            }
        });

        jTextField_VPW.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VPWKeyTyped(evt);
            }
        });

        jTextField_URL.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_URL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_URLActionPerformed(evt);
            }
        });
        jTextField_URL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_URLKeyTyped(evt);
            }
        });

        jTextField_VA.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_VAActionPerformed(evt);
            }
        });
        jTextField_VA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VAKeyTyped(evt);
            }
        });

        jLabelB.setFont(new java.awt.Font("Khmer MN", 1, 24)); // NOI18N
        jLabelB.setForeground(new java.awt.Color(204, 255, 255));
        jLabelB.setText(">>Back");
        jLabelB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBMouseExited(evt);
            }
        });

        jButtonEnter3.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter3.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter3.setText("Enter");
        jButtonEnter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("VRP :");

        jTextField_VRP.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VRP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VRPKeyTyped(evt);
            }
        });

        jButtonEnter2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter2.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter2.setText("Enter");
        jButtonEnter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter2ActionPerformed(evt);
            }
        });

        jButtonEnter0.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter0.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter0.setText("Enter");
        jButtonEnter0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter0ActionPerformed(evt);
            }
        });

        jButtonEnter1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter1.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter1.setText("Enter");
        jButtonEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter1ActionPerformed(evt);
            }
        });

        jButtonEnter4.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter4.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter4.setText("Enter");
        jButtonEnter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Ventricular Sensitivity :");

        jTextField_VS.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_VS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VSKeyTyped(evt);
            }
        });

        jButtonEnter5.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter5.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter5.setText("Enter");
        jButtonEnter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Hysteresis :");

        jLabel11.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Rate Smoothing :");

        jTextField_HY.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_HY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_HYKeyTyped(evt);
            }
        });

        jTextField_RT.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_RT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_RTKeyTyped(evt);
            }
        });

        jButtonEnter6.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter6.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter6.setText("Enter");
        jButtonEnter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter6ActionPerformed(evt);
            }
        });

        jButtonEnter7.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter7.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter7.setText("Enter");
        jButtonEnter7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter7ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Activity Threshold :");

        jTextField_AT.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_AT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ATActionPerformed(evt);
            }
        });
        jTextField_AT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ATKeyTyped(evt);
            }
        });

        jButtonEnter8.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter8.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter8.setText("Enter");
        jButtonEnter8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter8ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Reaction Time :");

        jTextField_RS.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_RS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_RSKeyTyped(evt);
            }
        });

        jButtonEnter9.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter9.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter9.setText("Enter");
        jButtonEnter9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter9ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("Response Factor :");

        jLabel15.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("Recovery Time :");

        jTextField_RF.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_RF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_RFKeyTyped(evt);
            }
        });

        jTextField_CT.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_CT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CTKeyTyped(evt);
            }
        });

        jButtonEnter10.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter10.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter10.setText("Enter");
        jButtonEnter10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter10ActionPerformed(evt);
            }
        });

        jButtonEnter11.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButtonEnter11.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEnter11.setText("Enter");
        jButtonEnter11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnter11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel3)))
                                                    .addComponent(jLabel4)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel6)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel11)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel14)
                                                            .addComponent(jLabel15)))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jLabel10)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(39, 39, 39)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_HY, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_VA, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_VPW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_VS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_VRP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_RT, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_AT, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_RS, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_RF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_CT, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel5)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnter11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter0, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabelB)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_LRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter0))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter1))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_VA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter2))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_VPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_VS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter4))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_VRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEnter3)
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_HY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnter6))))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_RT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter7))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_AT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter8))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_RS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter9))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_RF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter10))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_CT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelB)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_URLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_URLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_URLActionPerformed

    private void jTextField_VAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_VAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_VAActionPerformed

    private void jButtonEnter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter3ActionPerformed
        String APW = jTextField_VPW.getText();
        float apw = Float.valueOf(APW);
        
        if("0.05".equals(APW)){
            vvir_VPW.put(Login_Form.getusername() ,APW);
        jTextField_VPW.setText(vvir_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else if(apw>0.1 && apw<1.9 && (apw*100)%10==0){
            vvir_VPW.put(Login_Form.getusername() , APW);
        jTextField_VPW.setText(vvir_VPW.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
        }else{JOptionPane.showMessageDialog(null, "Out of range, The value must between 0.1to 1.9 the increment is 0.1 or 0.05"," Error", 3 );}
    }//GEN-LAST:event_jButtonEnter3ActionPerformed

    private void jLabelBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBMouseClicked
        Menu_Form form = new Menu_Form();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
    }//GEN-LAST:event_jLabelBMouseClicked

    private void jButtonEnter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter2ActionPerformed
        String VA  = jTextField_VA.getText();
         float va = Float.valueOf(VA);
         if ((va>0.5 && va<3.2 && (va*100)%10==0)){
        vvir_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(vvir_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (va>3.5 && va<7 && va%0.5==0){
        vvir_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(vvir_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 ); 
    }else if (va==0){
        vvir_VA.put(Login_Form.getusername() , VA);
        jTextField_VA.setText(vvir_VA.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "the input is OFF, 0.5V-3.2V with increment of 0.1V. in between 3.5V-7.0V with increment of 0.5V.  ","Error", 3 );}
    }//GEN-LAST:event_jButtonEnter2ActionPerformed

    private void jButtonEnter0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter0ActionPerformed
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        //System.out.println(lrl);
        
        if ((lrl>50 && lrl<90 && lrl%1==0)){
        vvir_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(vvir_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (lrl>30 && lrl<50 && lrl%5==0){
        vvir_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(vvir_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (lrl>90 && lrl<175 && lrl%5==0){
        vvir_LRL.put(Login_Form.getusername() , LRL);
        jTextField_LRL.setText(vvir_LRL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}
    }//GEN-LAST:event_jButtonEnter0ActionPerformed

    private void jButtonEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter1ActionPerformed
        String URL = jTextField_URL.getText();
        int url = Integer.parseInt(URL);
        String LRL = jTextField_LRL.getText();
        int lrl = Integer.parseInt(LRL);
        if (lrl>url){
            JOptionPane.showMessageDialog(null, "The upper rate limit is smaller than lower","Error", 3 );
        }else if (url<50 || url>175 || url%5!=0 || URL.trim().equals("")){
        JOptionPane.showMessageDialog(null, "Out of range, The value must between 50 to 175 the increment is 5","Error", 3 );
    }else{ vvir_URL.put(Login_Form.getusername() , URL);
        jTextField_URL.setText(vvir_URL.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButtonEnter1ActionPerformed

    private void jLabelBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBMouseEntered
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabelB.setBorder(label_border);
    }//GEN-LAST:event_jLabelBMouseEntered

    private void jLabelBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBMouseExited
        Border label_create_accont_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabelB.setBorder(label_create_accont_border);
    }//GEN-LAST:event_jLabelBMouseExited

    private void jTextField_LRLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LRLKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_LRLKeyTyped

    private void jTextField_URLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_URLKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_URLKeyTyped

    private void jTextField_VAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VAKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_VAKeyTyped

    private void jTextField_VPWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VPWKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField_VPWKeyTyped

    private void jButtonEnter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter4ActionPerformed
        String VS = jTextField_VS.getText();
        float vs = Float.valueOf(VS);
        if (vs==0.25 || vs==0.5 || vs==0.75){
        vvir_VS.put(Login_Form.getusername() , VS);
        jTextField_VS.setText(vvir_VS.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       } else if (vs<=10 && vs>=1.0 && vs%0.5==0){
         vvir_VS.put(Login_Form.getusername() , VS); 
         jTextField_VS.setText(vvir_VS.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 1to 10, the increment is 0.5 or it is 0.25.0.5 0.75 "," Error", 3 );
       }
    }//GEN-LAST:event_jButtonEnter4ActionPerformed

    private void jTextField_VRPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VRPKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_VRPKeyTyped

    private void jTextField_VSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VSKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_VSKeyTyped

    private void jButtonEnter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter5ActionPerformed
        String VRP = jTextField_VRP.getText();
        float vrp = Float.valueOf(VRP);
        
        if (vrp<150 || vrp>500 || vrp%10 !=0){
        JOptionPane.showMessageDialog(null, "Out of range, The value must between 150to 500, the increment is 10 "," Error", 3 );
    }else{ vvir_VRP.put(Login_Form.getusername() , VRP);
        jTextField_VRP.setText(vvir_VRP.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );}
    }//GEN-LAST:event_jButtonEnter5ActionPerformed

    private void jTextField_HYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HYKeyTyped
         if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_HYKeyTyped

    private void jTextField_RTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_RTKeyTyped
         if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_RTKeyTyped

    private void jButtonEnter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter6ActionPerformed
        String HY = jTextField_HY.getText();
        int hy = Integer.parseInt(HY);
        //System.out.println(lrl);
        
        if ((hy>50 && hy<90 && hy%1==0)){
        vvir_HY.put(Login_Form.getusername() , HY);
        jTextField_HY.setText(vvir_HY.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else if (hy>30 && hy<50 && hy%5==0){
        vvir_HY.put(Login_Form.getusername() , HY);
        jTextField_HY.setText(vvir_HY.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
     
    }else if (hy>90 && hy<175 && hy%5==0){
        vvir_HY.put(Login_Form.getusername() , HY);
        jTextField_HY.setText(vvir_HY.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
    }else{JOptionPane.showMessageDialog(null, "If the input range between 30-50 ppm and the increment is 5 ppm or in range of 50-90 ppm and increment is1 ppm.  Or in between 90-175 ppm and the increment is 5 ppm. ","Error", 3 );}
    }//GEN-LAST:event_jButtonEnter6ActionPerformed

    private void jButtonEnter7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter7ActionPerformed
       
        String RT = jTextField_RT.getText();
        int rt = Integer.parseInt(RT);
        if (rt>=10 && rt<=50 && rt%10==0){
        vvir_RT.put(Login_Form.getusername() , RT);
        jTextField_RT.setText(vvir_RT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 10to 50, the increment is 10 "," Error", 3 );
       }
    }//GEN-LAST:event_jButtonEnter7ActionPerformed

    private void jTextField_ATKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ATKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ATKeyTyped

    private void jButtonEnter8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter8ActionPerformed
         String AT = jTextField_AT.getText();
   
        if ("V-low".equals(AT) || "Low".equals(AT)|| "Med-Low".equals(AT) || "Med".equals(AT) || "Med-High".equals(AT) || "High".equals(AT)|| "V-High".equals(AT) ){
        vvir_AT.put(Login_Form.getusername() , AT);
        jTextField_AT.setText(vvir_AT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must be V-Low, Low, Med-Low, Med,Med-High, High, V-High "," Error", 3 );
       }
    }//GEN-LAST:event_jButtonEnter8ActionPerformed

    private void jTextField_RSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_RSKeyTyped
         if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_RSKeyTyped

    private void jButtonEnter9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter9ActionPerformed
        String RS = jTextField_RS.getText();
        int rs = Integer.parseInt(RS);
        if (rs==0 || rs==3|| rs==6|| rs==9|| rs==12|| rs==15|| rs==18|| rs==21|| rs==25 ){
        vvir_RS.put(Login_Form.getusername() , RS);
        jTextField_RS.setText(vvir_RS.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must be0, 3, 6, 9, 12, 15, 18, 21,25 "," Error", 3 );
       }
        
    }//GEN-LAST:event_jButtonEnter9ActionPerformed

    private void jTextField_RFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_RFKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_RFKeyTyped

    private void jTextField_CTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CTKeyTyped
         if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_CTKeyTyped

    private void jButtonEnter10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter10ActionPerformed
        String RF = jTextField_RF.getText();
        int rf = Integer.parseInt(RF);
        if (rf>=1 && rf<=16 && rf%1==0){
        vvir_RF.put(Login_Form.getusername() , RF);
        jTextField_RF.setText(vvir_RF.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 1to 16, the increment is 1 "," Error", 3 );
       }
    }//GEN-LAST:event_jButtonEnter10ActionPerformed

    private void jButtonEnter11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnter11ActionPerformed
        String CT = jTextField_CT.getText();
        int ct = Integer.parseInt(CT);
        if (ct>=2 && ct<=16 && ct%1==0){
        vvir_CT.put(Login_Form.getusername() , CT);
        jTextField_CT.setText(vvir_CT.get(Login_Form.getusername(),""));
        JOptionPane.showMessageDialog(null, "Value Input Successful",Login_Form.getusername(), 3 );
       }else {JOptionPane.showMessageDialog(null, "Out of range, The value must between 2to 16, the increment is 1 "," Error", 3 );
       }
    }//GEN-LAST:event_jButtonEnter11ActionPerformed

    private void jTextField_ATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ATActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVIR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter0;
    private javax.swing.JButton jButtonEnter1;
    private javax.swing.JButton jButtonEnter10;
    private javax.swing.JButton jButtonEnter11;
    private javax.swing.JButton jButtonEnter2;
    private javax.swing.JButton jButtonEnter3;
    private javax.swing.JButton jButtonEnter4;
    private javax.swing.JButton jButtonEnter5;
    private javax.swing.JButton jButtonEnter6;
    private javax.swing.JButton jButtonEnter7;
    private javax.swing.JButton jButtonEnter8;
    private javax.swing.JButton jButtonEnter9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_AT;
    private javax.swing.JTextField jTextField_CT;
    private javax.swing.JTextField jTextField_HY;
    private javax.swing.JTextField jTextField_LRL;
    private javax.swing.JTextField jTextField_RF;
    private javax.swing.JTextField jTextField_RS;
    private javax.swing.JTextField jTextField_RT;
    private javax.swing.JTextField jTextField_URL;
    private javax.swing.JTextField jTextField_VA;
    private javax.swing.JTextField jTextField_VPW;
    private javax.swing.JTextField jTextField_VRP;
    private javax.swing.JTextField jTextField_VS;
    // End of variables declaration//GEN-END:variables
}
